# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apme/v1/ansible.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'apme/v1/ansible.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apme.v1 import common_pb2 as apme_dot_v1_dot_common__pb2
from apme.v1 import validate_pb2 as apme_dot_v1_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61pme/v1/ansible.proto\x12\x07\x61pme.v1\x1a\x14\x61pme/v1/common.proto\x1a\x16\x61pme/v1/validate.proto2\x85\x01\n\x07\x41nsible\x12?\n\x08Validate\x12\x18.apme.v1.ValidateRequest\x1a\x19.apme.v1.ValidateResponse\x12\x39\n\x06Health\x12\x16.apme.v1.HealthRequest\x1a\x17.apme.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apme.v1.ansible_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANSIBLE']._serialized_start=81
  _globals['_ANSIBLE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
